{'name': 'Aplicação para Admissão a Dissertação',
 'description': 'Gestão do processo de admissão à dissertação',
 'depends': ['base', 'gestao_dissertacoes'],
 'data': [
     'security/dissertation_admission_security_groups.xml',
     'security/dissertation_admission_security_dissertation.xml',
     'security/dissertation_admission_security_work_plan.xml',
     'security/dissertation_admission_security_student.xml',
     'security/dissertation_admission_security_adviser.xml',
     'security/ir.model.access.csv',
     'wizards/publish_dissertation_wizard.xml',
     'wizards/sign_wizard.xml',
     'wizards/make_review_wizard.xml',
     'wizards/upload_work_plan_wizard.xml',
     'views/dissertation_admission_menu.xml',
     'views/student_view.xml',
     'views/adviser_view.xml',
     'views/direction_view.xml',
     'views/company_view.xml',
     'views/company_employee_view.xml',
     'views/dissertation_view.xml',
     'views/reviews_view.xml',
     'views/work_plan_view.xml',
     'views/course_view.xml',
#     'demo/course.xml',
#     'demo/user.xml',
 ],
 'application': True,
 'installable': True,
 }
