{'name': 'Aplicação para Admissão a Dissertação',
 'description': 'Gestão do processo de admissão à dissertação',
 'depends': ['base'],
 'data': [
     'security/dissertation_admission_security_groups.xml',
     'security/dissertation_admission_security_dissertation.xml',
     'security/dissertation_admission_security_work_plan.xml',
     'security/ir.model.access.csv',
     'views/dissertation_admission_menu.xml',
     'views/student_view.xml',
     'views/adviser_view.xml',
     'views/direction_view.xml',
     'views/company_view.xml',
     'views/company_employee_view.xml',
     'views/dissertation_view.xml',
     'views/reviews_view.xml',
     'views/work_plan_view.xml',
     'views/course_view.xml',
     'views/department_view.xml',
     'views/investigation_center_view.xml',
     'demo/course.xml',
     'demo/department.xml',
     'demo/investigation_center.xml',
     'demo/user.xml',
     'demo/student.xml'
 ],
 'application': True,
 'installable': True,
 }
